//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class BasicData
    {
        public int ID { get; set; }
        public string GroupType { get; set; }
        public string Title { get; set; }
        public string Title_EN { get; set; }
        public string GroupTypeName { get; set; }
        public string GroupTypeName_En { get; set; }
        public Nullable<int> CodeINT { get; set; }
        public string CodeChar { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<bool> Show { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string LogUser { get; set; }
        public Nullable<bool> IsDefault { get; set; }
    }
}
