//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CompanyTransportation
    {
        public int ID { get; set; }
        public int CompanyID { get; set; }
        public int TransportationCalculate_BasicData { get; set; }
        public string Title { get; set; }
        public Nullable<decimal> Factor { get; set; }
        public Nullable<decimal> TransportationPrice { get; set; }
        public Nullable<bool> IsFree { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string LogUser { get; set; }
    }
}
