//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PageGenerator
    {
        public int ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string PageTitle { get; set; }
        public Nullable<int> PageLocationID { get; set; }
        public string PageLocation { get; set; }
        public string PageContent { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<int> PageSystemCode { get; set; }
    }
}
