//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<decimal> Amount { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string CreateDate_Shamsi { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<int> PaymentType { get; set; }
        public string Description { get; set; }
        public string BankName { get; set; }
        public string Error { get; set; }
        public string BankRefrence { get; set; }
        public string Token { get; set; }
    }
}
