//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductGroupDetail
    {
        public int ID { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public string GroupTypeName { get; set; }
        public Nullable<bool> IsShowSearch { get; set; }
        public string GroupTypeName_En { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsShowEasySearch { get; set; }
    }
}
