//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Product()
        {
            this.ProductDescriptions = new HashSet<ProductDescription>();
            this.ProductUserComments = new HashSet<ProductUserComment>();
            this.ProductDetails = new HashSet<ProductDetail>();
        }
    
        public int ID { get; set; }
        public Nullable<int> ParentID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> ProductGroupID { get; set; }
        public Nullable<decimal> PriceBuy { get; set; }
        public Nullable<int> OffPercent { get; set; }
        public Nullable<decimal> PriceSales { get; set; }
        public string Currency { get; set; }
        public Nullable<int> Positive { get; set; }
        public Nullable<int> Negative { get; set; }
        public Nullable<System.DateTime> CreaeDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string LogUser { get; set; }
        public Nullable<bool> Acive { get; set; }
        public Nullable<bool> IsAvailable { get; set; }
        public Nullable<int> AvailableCount { get; set; }
        public Nullable<int> SalesCount { get; set; }
        public Nullable<bool> IsSpecialSales { get; set; }
        public Nullable<System.DateTime> FromDateSpecialSales_Mila { get; set; }
        public string FromDateSpecialSales { get; set; }
        public Nullable<System.DateTime> ToDateSpecialSales_Mila { get; set; }
        public string ToDateSpecialSales { get; set; }
        public string BarCode { get; set; }
        public string ImageUrl { get; set; }
        public string Name { get; set; }
        public string SumerySpecification { get; set; }
        public Nullable<bool> IsViewInstagram { get; set; }
        public Nullable<bool> IsViewTelegram { get; set; }
        public Nullable<bool> IsSendInstagram { get; set; }
        public Nullable<bool> IsSendTelegram { get; set; }
        public string TelegramError { get; set; }
        public string InstagramError { get; set; }
        public string InstagramTag { get; set; }
        public Nullable<System.DateTime> TelegramTimeSend { get; set; }
        public Nullable<System.DateTime> IstagramTimeSend { get; set; }
        public Nullable<bool> IsOffPercent { get; set; }
        public Nullable<int> VisitedCount { get; set; }
        public Nullable<int> TransportationID { get; set; }
    
        public virtual Currency Currency1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDescription> ProductDescriptions { get; set; }
        public virtual ProductGroup ProductGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductUserComment> ProductUserComments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductDetail> ProductDetails { get; set; }
    }
}
