//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Purchase
    {
        public int ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> Status { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public string DateShamsi { get; set; }
        public Nullable<decimal> Total { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> TotalDiscount { get; set; }
        public string DiscountCode { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Description_Admin { get; set; }
        public string LogUser { get; set; }
        public Nullable<decimal> TransportationAmount { get; set; }
    }
}
