//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class PurchaseDetail
    {
        public int ID { get; set; }
        public Nullable<int> PurchaseID { get; set; }
        public Nullable<int> ProductID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> ShoppingCount { get; set; }
        public string ProducName { get; set; }
        public Nullable<int> AvalaibleCount { get; set; }
        public Nullable<decimal> TotalPrice { get; set; }
        public Nullable<decimal> UnitDiscount { get; set; }
        public Nullable<decimal> TotalUnitDisount { get; set; }
    }
}
