//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserMenu
    {
        public int ID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string Title { get; set; }
        public string ControlID { get; set; }
        public string Lang { get; set; }
        public Nullable<int> Sort { get; set; }
        public Nullable<bool> IsShow { get; set; }
        public Nullable<bool> Active { get; set; }
    }
}
