//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserProfile
    {
        public int UserID { get; set; }
        public Nullable<int> CompanyID { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public Nullable<bool> Active { get; set; }
        public Nullable<System.DateTime> LastDateVisit { get; set; }
        public Nullable<System.DateTime> CreateDate { get; set; }
        public Nullable<System.DateTime> UpdateDate { get; set; }
        public string Name { get; set; }
        public string Family { get; set; }
        public string Mobile { get; set; }
        public string Email { get; set; }
        public string NationalCode { get; set; }
        public Nullable<int> Gender { get; set; }
        public Nullable<int> RoleID { get; set; }
        public string TokenID { get; set; }
        public string FullName_En { get; set; }
        public string Tell { get; set; }
        public string LogUser { get; set; }
    }
}
