//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserSubMenu
    {
        public int ID { get; set; }
        public Nullable<int> CompanyIDMenu { get; set; }
        public string TitleMenu { get; set; }
        public string ControlID { get; set; }
        public string SelectorID { get; set; }
        public string Lang { get; set; }
        public Nullable<int> SortMenu { get; set; }
        public Nullable<bool> IsShowMenu { get; set; }
        public Nullable<bool> ActiveMenu { get; set; }
    }
}
